### ISSUE TITLE
Getting a bunch of errors

### ISSUE THREAD

**Issue by aayush-g1414** [Harry-LowIQ/Solana-Coinflip#1]
Hello Harry, after I run "npm i" there are a bunch of errors relating to dependency. Additionally, if I try to do anchor build, it says that Anchor is not detected even though the environment has everything. Do you know how to fix these problems? Also if you have your own website that you published with this code, it would be nice if you could send the link so I could see how it works.

I appreciate any help, thanks!

**Comment by c-reetz** [comment]
I may have fucked the npm up as I just grabbed this out of another folder I had of projects, I'll look at it later :)
I have an example site at:
fuck-linus.vercel.app
Runs on devnet, outcome will never change as I botched the VRF integration there

**Comment by aayush-g1414** [comment]
Alright thanks, that makes sense. Please let me know when you change it or look at, hopefully it's soon! Thanks again for the response.

**Comment by c-reetz** [comment]
I had forgotten to include `Anchor.toml`
`anchor build` should work properly for you now.
`yarn install` installed the dependencies for the test for me - so I don't really know what happened on your side there.

**Comment by aayush-g1414** [comment]
Anchor build seems to be working, but anchor test gives this error... Error: Unable to open program file: No such file or directory (os error 2) There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }. Do you have a step by step for how you set up your environment so I can do the same? Also, how were you able to run it on vercel, I can't even get that to work.

**Comment by aayush-g1414** [comment]
A lot of the problems have to do with eslint which is something new to me, so maybe my environment is setup wrong

**Comment by c-reetz** [comment]
> A lot of the problems have to do with eslint which is something new to me, so maybe my environment is setup wrong

Don't think it's this, that's just formatter


> but anchor test gives this error... 

check line 26 in the test, the one where it says:
```
import {
  AnchorVrfParser,
  IDL,
} from "../target/types/anchor_vrf_parser";
```
You might have to change where it imports from

**Comment by c-reetz** [comment]
Also, for Vercel, try re-fetching repo and then see if you can upload it.

**Comment by aayush-g1414** [comment]
When you did it locally/through devnet, how did you set up your environment such as downloading rust, solana, node, mocha, openssl, libssl, etc? I feel like that could be the problem.

**Comment by c-reetz** [comment]
Rust through rustup or whatever it's called (Just default installer, newest version) Anchor through AVM, SOL through their CURL command in docs.
I don't do `npm i`, I do `yarn install` instead

**Comment by aayush-g1414** [comment]
Ah okay, so that's all you download before running anchor build and anchor test?

**Comment by aayush-g1414** [comment]
> Also, for Vercel, try re-fetching repo and then see if you can upload it.

Sorry I'm a bit new to using GitHub and Vercel, how would I do this exactly?

**Comment by aayush-g1414** [comment]
> You might have to change where it imports from

What would I change the import to?

**Comment by c-reetz** [comment]
> > Also, for Vercel, try re-fetching repo and then see if you can upload it.
> 
> 
> 
> Sorry I'm a bit new to using GitHub and Vercel, how would I do this exactly?

`git pull` should just working you've cloned this repo :)

**Comment by c-reetz** [comment]
> > You might have to change where it imports from
> 
> 
> 
> What would I change the import to?

Your path to where Anchor generates your `/target/types/anchor_vrf_parser`

**Comment by aayush-g1414** [comment]
Do you have discord or an email address so that I can contact you and we can get this all figured out? I have been trying everything and it still doesn't work, but I can see that your vercel works. Hopefully we can get in contact and get this working and I will give you some sol as a donation for your help.

**Comment by aayush-g1414** [comment]
Also I think you may have forgotten to copy over the eslint files or something because one way or another, it ends up being the problem.

**Comment by c-reetz** [comment]
> Also I think you may have forgotten to copy over the eslint files or something because one way or another, it ends up being the problem.

Just remove all mentions in the package files for it, then there's no lint to install.

**Comment by c-reetz** [comment]
> Do you have discord or an email address so that I can contact you and we can get this all figured out? I have been trying everything and it still doesn't work, but I can see that your vercel works. Hopefully we can get in contact and get this working and I will give you some sol as a donation for your help.

I am really busy with uni, so I won't be fast @ responses, but you can hit me up at:
Harry.#0777
